### ISSUE TITLE
Include option to force thresholds?

### ISSUE THREAD

**Issue by lirantal** [simonecorsi/lcov-total#9]
Hey Simone,

Thanks for this plugin.
I could see it useful for me in another project if it could not only read the coverage data (`lcov-total lcov.info`) but also allow to enforce it. Jest for example provide the thresholds rules like [this](https://jestjs.io/docs/en/configuration#coveragethreshold-object):
```json
{
  "jest": {
    "coverageThreshold": {
      "global": {
        "branches": 80,
        "functions": 80,
        "lines": 80,
        "statements": -10
      }
    }
  }
}
```

Since lcov-total can already read the data, it could be used in CI to fail/pass according to the thresholds set.

**Comment by Kirkhammetz** [comment]
Hey @lirantal,

if you need a way to fail/pass according to a threshold there is already a flag to do like so eg: `npx lcov-total lcov.info --gte=90` which will exit with code 1 or 0 based on a greater than equal condition check.

Is this what you were looking for? Or are you suggesting granular control over multiple conditions like jest?

**Comment by lirantal** [comment]
It's close to that. I don't want to specify the thresholds over command line but rather have lcov-total already take it from where it is defined in the package.json file. Jest puts it there as well as nyc.

**Comment by simonecorsi** [comment]
I'm really sorry I missed this issue for so long, it must have slipped in the notification panel :((

Anyway I've just moved this to ESM in the new major! 
If you still need this feel free to open a PR!

**Comment by lirantal** [comment]
Appreciate that, thank you Simone 🤗
